"""남도길담 코스 원천 데이터 (schema v3.1).

정본(single source of truth)은 Google Sheets `남도길담 관광·교통 데이터베이스`이며,
본 모듈은 시트의 `코스 요약`·`교통 구간`·`코스 일정`·`후보 장소`·`로컬 설명`·`식사 후보`·
`개발 JSON`·`대체·보류 코스` 탭을 코드로 옮긴 스냅샷입니다.

규칙
- ``publishable``·``exposureTier``·``isPrimary`` 는 시트 값을 그대로 유지합니다.
  추천 노출 여부는 코드가 임의로 판단하지 않고 ``exposure.py`` 정책이 결정합니다.
- ``totalMinutes.plan`` 은 ``itinerary`` 소요시간 합계와 일치해야 하며
  ``schema.py`` 의 정합성 검사가 이를 강제합니다.
- 날짜 종속 정보(열차 회차, 현장예매, 임시휴무)는 확정값으로 표기하지 않고
  ``manualChecks`` 로 분리합니다.
- 귀가 교통은 시트의 마지막 구간ID를 참조하는 ``returnTransport``에
  배차형·계획회차형·예약형으로 보존합니다. 배차간격을 막차로 해석하지 않습니다.
- Track #1 원자료의 실제 사용상태는 ``lineage.py``에서 별도로 관리합니다.
"""

from typing import Any

SCHEMA_VERSION = "3.1"
DATA_SNAPSHOT_DATE = "2026-08-06"
DATA_SOURCE_NAME = "남도길담 관광·교통 데이터베이스 (Google Sheets, 정본)"
DATA_SOURCE_URL = (
    "https://docs.google.com/spreadsheets/d/"
    "1o8xeUEJzt0rai4_Wn73idVLke4meesglSrSWscN5i6E/edit"
)

DEPARTURE_POINTS: dict[str, dict[str, Any]] = {
    "USQUARE": {
        "id": "USQUARE",
        "name": "유스퀘어(광주종합버스터미널)",
        "latitude": 35.16018,
        "longitude": 126.87849,
    },
    "GWANGJU_SONGJEONG": {
        "id": "GWANGJU_SONGJEONG",
        "name": "광주송정역",
        "latitude": 35.13600,
        "longitude": 126.79132,
    },
}


COURSE_DETAILS: list[dict[str, Any]] = [
    # ------------------------------------------------------------------
    # DY_LOW_01
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "DY_LOW_01",
        "title": "담양 읍내 저도보 산책 코스",
        "region": "담양",
        "courseType": "LOW_FATIGUE",
        "departurePoint": "USQUARE",
        "applicableDays": ["SATURDAY"],
        "timeType": "SIX_HOURS",
        "verificationStatus": "PARTIALLY_VERIFIED",
        "publishable": False,
        "exposureTier": "MANUAL_REVIEW",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-damyang.svg",
        "tags": ["자연·산책", "음식·시장", "감성기록"],
        "preferences": ["NATURE_WALK", "FOOD_MARKET", "MEMORY"],
        "totalMinutes": {"min": 323, "plan": 354, "max": 396},
        "walkingMinutes": {"min": 11, "plan": 14, "max": 16},
        "insideWalkingMinutes": 11,
        "transferCount": 0,
        "roundTripTransitMinutes": 140,
        "localTransitMinutes": 0,
        "stayMinutes": 200,
        "sheetFatigueLevel": "MEDIUM",
        "schedule": {
            "departureTime": "09:00",
            "plannedReturnTime": "14:54",
            "latestReturnTime": "15:36",
            "returnLegMinutes": {"min": 55, "plan": 70, "max": 90},
            "returnTransport": {
                "type": "HEADWAY_SERVICE",
                "segmentId": "DY_LOW_01-S2",
                "serviceDay": "SATURDAY",
                "plannedDeparture": None,
                "plannedBoardingAfter": "13:44",
                "alternativeDepartures": [],
                "departureWindow": {"start": "13:30", "end": None},
                "headwayMinutes": 20,
                "ticketingModel": "PAY_ON_BOARD",
                "stationArrivalBufferMinutes": 0,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "OFFICIAL_BIS+USER_VERIFIED",
                "operatingModel": "주말 20분 배차형",
                "note": "13:30 이후 담양311 도착정보를 BIS에서 확인하고 탑승합니다.",
            },
            "bookingRequired": False,
            "bookingNote": None,
            "returnBufferMinutes": 0,
        },
        "recommendationReasons": [
            "환승 없이 담양 읍내 핵심을 연결하며 관광지 사이 이동 도보는 계획 14분입니다.",
            "관방제림·국수거리·죽녹원이 한 동선에 있어 되돌아가는 구간이 없습니다.",
            "계획 기준 14:54 광주 도착으로 6시간 안에 귀가할 수 있습니다.",
        ],
        "description": "향교다리에서 내려 관방제림·국수거리·죽녹원을 이동 도보 14분으로 잇는 담양 읍내 코스입니다.",
        "cautions": [
            "죽녹원 내부 보행 약 11분은 이동 도보와 분리해 계산했습니다.",
            "311-1 대체 운행 시 탑승시간이 최대 70분까지 늘어날 수 있습니다.",
        ],
        "manualChecks": [
            "당일 311/311-1 도착정보",
            "죽녹원 정문·매표소 기준 도보 2건",
            "식사 후보 임시휴무·대기",
        ],
        "itinerary": [
            {
                "id": "DY_LOW_01-S1",
                "time": "09:00",
                "name": "유스퀘어 → 향교다리",
                "type": "transport",
                "durationMinutes": 70,
                "note": "담양311(311-1 대체) 광천터미널 2002 승차. 주말 20분 배차형.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "향교다리 정류소", "latitude": 35.32307, "longitude": 126.98487},
            },
            {
                "id": "DY_LOW_01-W1",
                "time": "10:10",
                "name": "향교다리 → 관방제림 입구",
                "type": "walk",
                "durationMinutes": 2,
                "note": "104m·2분(카카오맵 실측).",
                "segmentType": "FIXED_MAP",
                "verificationStatus": "VERIFIED_MAP",
            },
            {
                "id": "DY-002",
                "time": "10:12",
                "name": "관방제림",
                "type": "place",
                "durationMinutes": 50,
                "note": "담양천 제방을 따라 걷는 상시 개방·무료 구간입니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "담양 관방제림", "latitude": 35.32418, "longitude": 126.98556},
            },
            {
                "id": "DY_LOW_01-W2",
                "time": "11:02",
                "name": "관방제림 → 담양 국수거리",
                "type": "walk",
                "durationMinutes": 3,
                "note": "천변 인접 구간.",
                "segmentType": "FIXED_PLAN",
                "verificationStatus": "VERIFIED",
            },
            {
                "id": "DY-003",
                "time": "11:05",
                "name": "담양 국수거리",
                "type": "food",
                "durationMinutes": 60,
                "note": "지정 점포가 아니라 후보 9곳 중 당일 영업·대기 상황이 좋은 곳을 선택합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "담양 국수거리", "latitude": 35.32392, "longitude": 126.98668},
            },
            {
                "id": "DY_LOW_01-W3",
                "time": "12:05",
                "name": "담양 국수거리 → 죽녹원 정문·매표소",
                "type": "walk",
                "durationMinutes": 7,
                "note": "향교교 경유 약 300m 추정값. 지도 실측 대기 구간입니다.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "DY-001",
                "time": "12:12",
                "name": "죽녹원",
                "type": "place",
                "durationMinutes": 90,
                "note": "내부 경사 숲길 보행 약 11분을 체류시간에 포함했습니다. 성인 3,000원.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "담양 죽녹원", "latitude": 35.32720, "longitude": 126.98853},
            },
            {
                "id": "DY_LOW_01-W4",
                "time": "13:42",
                "name": "죽녹원 정문 → 죽녹원 정류소(광주방향)",
                "type": "walk",
                "durationMinutes": 2,
                "note": "163m, 횡단 없음.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "DY_LOW_01-S2",
                "time": "13:44",
                "name": "죽녹원 정류소 → 신세계백화점(2276)",
                "type": "transport",
                "durationMinutes": 70,
                "note": "담양311 광주방향. 당일 BIS 도착정보 확인 후 탑승.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {
                    "name": "유스퀘어(광주종합버스터미널)",
                    "latitude": 35.16018,
                    "longitude": 126.87849,
                },
            },
        ],
        "localFood": [
            {
                "id": "DY_MEAL_01",
                "name": "원조대나무국수",
                "description": "08:30~20:00, 연중무휴. 영업 중이며 대기 20분 이하이면 1순위로 선택합니다.",
                "tags": ["담양 국수거리", "1순위"],
            },
            {
                "id": "DY_MEAL_02",
                "name": "담양막둥이국수 죽녹원국수거리본점",
                "description": "10:00~20:00, 매주 화요일 휴무, 라스트오더 19:30. 1순위 휴무·만석 시 선택합니다.",
                "tags": ["담양 국수거리", "2순위"],
            },
            {
                "id": "DY_MEAL_03",
                "name": "옛날진미국수",
                "description": "09:00~20:00, 매주 수요일 휴무. 앞선 후보 대기시간이 길 때 선택합니다.",
                "tags": ["담양 국수거리", "3순위"],
            },
        ],
        "localPoints": [
            {
                "id": "DY-002",
                "title": "향교다리에서 바로 시작하는 제방길",
                "description": "담양천 제방을 보호하려고 조성된 오래된 숲으로, 정류소와 가까워 하차 뒤 부담 없이 시작할 수 있습니다.",
                "tags": ["자연·산책"],
            },
            {
                "id": "DY-003",
                "title": "동선을 늘리지 않는 음식 구역",
                "description": "국수거리가 관방제림과 붙어 있어 이동을 거의 늘리지 않고 지역 음식을 경험할 수 있습니다.",
                "tags": ["음식·시장"],
            },
        ],
        "scenePrompts": [
            "담양천과 고목이 한 화면에 들어오는 제방길",
            "천변 평상과 국수 한 그릇이 함께 보이는 장면",
            "대나무 사이로 빛이 길게 들어오는 순간",
        ],
        "primaryDestination": {
            "name": "담양 관방제림",
            "latitude": 35.32418,
            "longitude": 126.98556,
        },
        "sources": [
            {
                "label": "담양군 버스정보시스템",
                "url": "http://bis.damyang.go.kr/busmap/lineSearch",
                "checkedDate": "2026-08-02",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "label": "죽녹원 공식 홈페이지",
                "url": "https://www.juknokwon.go.kr",
                "checkedDate": "2026-08-01",
                "verificationStatus": "VERIFIED",
            },
            {
                "label": "국가유산포털(관방제림)",
                "url": "https://www.heritage.go.kr",
                "checkedDate": "2026-08-01",
                "verificationStatus": "VERIFIED",
            },
        ],
    },
    # ------------------------------------------------------------------
    # DY_NORMAL_01
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "DY_NORMAL_01",
        "title": "담양 대나무 문화 확장 코스",
        "region": "담양",
        "courseType": "NORMAL",
        "departurePoint": "USQUARE",
        "applicableDays": ["SATURDAY"],
        "timeType": "FULL_DAY",
        "verificationStatus": "PARTIALLY_VERIFIED",
        "publishable": False,
        "exposureTier": "DEMO_ONLY",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-damyang.svg",
        "tags": ["자연·산책", "역사·문화", "음식·시장"],
        "preferences": ["NATURE_WALK", "HISTORY_CULTURE", "FOOD_MARKET"],
        "totalMinutes": {"min": 432, "plan": 462, "max": 492},
        "walkingMinutes": {"min": 42, "plan": 52, "max": 62},
        "insideWalkingMinutes": 15,
        "transferCount": 0,
        "roundTripTransitMinutes": 140,
        "localTransitMinutes": 20,
        "stayMinutes": 250,
        "sheetFatigueLevel": "HIGH",
        "schedule": {
            "departureTime": "08:30",
            "plannedReturnTime": "16:12",
            "latestReturnTime": "16:42",
            "returnLegMinutes": {"min": 55, "plan": 70, "max": 85},
            "returnTransport": {
                "type": "HEADWAY_SERVICE",
                "segmentId": "DY_LOW_01-S2",
                "serviceDay": "SATURDAY",
                "plannedDeparture": None,
                "plannedBoardingAfter": "15:02",
                "alternativeDepartures": [],
                "departureWindow": {"start": "13:30", "end": None},
                "headwayMinutes": 20,
                "ticketingModel": "PAY_ON_BOARD",
                "stationArrivalBufferMinutes": 0,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "OFFICIAL_BIS+USER_VERIFIED",
                "operatingModel": "주말 20분 배차형",
                "note": "DY_LOW_01-S2 귀가 구간을 공유하며 당일 BIS 도착정보를 확인합니다.",
            },
            "bookingRequired": False,
            "bookingNote": None,
            "returnBufferMinutes": 0,
        },
        "recommendationReasons": [
            "한국대나무박물관과 담양 읍내 핵심 관광지를 하루 일정으로 연결합니다.",
            "실내 전시가 포함되어 우천·폭염 시에도 일정을 유지할 수 있습니다.",
            "환승 없이 311 계열과 읍내 버스만으로 이동합니다.",
        ],
        "description": "대나무 산업·공예 전시를 먼저 보고 읍내 자연과 음식으로 이어지는 하루 종일 코스입니다.",
        "cautions": [
            "총 도보 계획 52분으로 이동 부담이 큰 편입니다.",
            "담양터미널~박물관 도보 20분은 대표 위치 기준 추정값입니다.",
        ],
        "manualChecks": [
            "한국대나무박물관 운영 공지·임시휴관",
            "담양터미널~박물관 출입구 기준 도보",
            "당일 311 도착정보",
        ],
        "itinerary": [
            {
                "id": "DY_NORMAL_01-S1",
                "time": "08:30",
                "name": "유스퀘어 → 담양공용버스터미널",
                "type": "transport",
                "durationMinutes": 70,
                "note": "담양311 승차. 먼저 도착하는 311 계열을 이용합니다.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "담양공용버스터미널", "latitude": 35.32107, "longitude": 126.98836},
            },
            {
                "id": "DY_NORMAL_01-W1",
                "time": "09:40",
                "name": "담양터미널 → 한국대나무박물관",
                "type": "walk",
                "durationMinutes": 20,
                "note": "대표 위치 기준 계획값. 출입구 기준 재검수 필요.",
                "segmentType": "FIXED_PLAN",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "DY-006",
                "time": "10:00",
                "name": "한국대나무박물관",
                "type": "place",
                "durationMinutes": 60,
                "note": "09:00~18:00, 입장마감 17:30, 성인 2,000원.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "한국대나무박물관", "latitude": 35.30737, "longitude": 127.00383},
            },
            {
                "id": "DY_NORMAL_01-W2",
                "time": "11:00",
                "name": "박물관 → 백동사거리 정류소",
                "type": "walk",
                "durationMinutes": 11,
                "note": "읍내 버스 승차 지점까지 이동.",
                "segmentType": "RANGE",
                "verificationStatus": "VERIFIED_MAP",
            },
            {
                "id": "DY_NORMAL_01-W2-TRANSIT",
                "sourceRecordId": "DY_NORMAL_01-W2",
                "time": "11:11",
                "name": "백동사거리 → 관방제림",
                "type": "transport",
                "durationMinutes": 20,
                "note": "읍내 연결 버스. 배차 20분 기준 대기 포함.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "DY-002",
                "time": "11:31",
                "name": "관방제림",
                "type": "place",
                "durationMinutes": 45,
                "note": "저도보 코스와 동일 구간이며 체류를 45분으로 줄였습니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "담양 관방제림", "latitude": 35.32418, "longitude": 126.98556},
            },
            {
                "id": "DY_NORMAL_01-W3",
                "time": "12:16",
                "name": "관방제림 → 담양 국수거리",
                "type": "walk",
                "durationMinutes": 3,
                "note": "천변 인접 구간.",
                "segmentType": "FIXED_PLAN",
                "verificationStatus": "VERIFIED",
            },
            {
                "id": "DY-003",
                "time": "12:19",
                "name": "담양 국수거리",
                "type": "food",
                "durationMinutes": 60,
                "note": "저도보 코스와 동일한 후보군(DY_MEAL_01~09)을 사용합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "담양 국수거리", "latitude": 35.32392, "longitude": 126.98668},
            },
            {
                "id": "DY_NORMAL_01-W4",
                "time": "13:19",
                "name": "담양 국수거리 → 죽녹원",
                "type": "walk",
                "durationMinutes": 11,
                "note": "641m·11분, 카카오맵 대표 POI 기준.",
                "segmentType": "FIXED_MAP",
                "verificationStatus": "VERIFIED_MAP",
            },
            {
                "id": "DY-001",
                "time": "13:30",
                "name": "죽녹원",
                "type": "place",
                "durationMinutes": 85,
                "note": "내부 숲길 보행을 체류시간에 포함했습니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "담양 죽녹원", "latitude": 35.32720, "longitude": 126.98853},
            },
            {
                "id": "DY_NORMAL_01-W5",
                "time": "14:55",
                "name": "죽녹원 → 죽녹원 정류소",
                "type": "walk",
                "durationMinutes": 7,
                "note": "광주방향 정류소로 이동.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "DY_NORMAL_01-RETURN",
                "sourceRecordId": "DY_LOW_01-S2",
                "time": "15:02",
                "name": "죽녹원 정류소 → 신세계백화점(2276)",
                "type": "transport",
                "durationMinutes": 70,
                "note": "담양311 광주방향.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {
                    "name": "유스퀘어(광주종합버스터미널)",
                    "latitude": 35.16018,
                    "longitude": 126.87849,
                },
            },
        ],
        "localFood": [
            {
                "id": "DY_MEAL_SHARED",
                "name": "담양 국수거리 후보군(DY_MEAL_01~09)",
                "description": "9곳 중 당일 영업이 확인된 곳을 선택하며, 최소 2곳 영업이 확인될 때만 코스를 유지합니다.",
                "tags": ["담양 국수거리", "공유 후보군"],
            },
        ],
        "localPoints": [
            {
                "id": "DY-006",
                "title": "자연 체험을 문화·산업 맥락으로 확장",
                "description": "죽녹원의 대나무 숲 경험을 공예·산업·생활문화 전시로 이어서 이해할 수 있습니다.",
                "tags": ["역사·문화"],
            },
        ],
        "scenePrompts": [
            "대나무 공예품의 반복되는 결 무늬",
            "전시물과 실제 대나무 재료가 함께 보이는 장면",
            "나무 그늘 아래 길게 이어지는 산책로",
        ],
        "primaryDestination": {
            "name": "한국대나무박물관",
            "latitude": 35.30737,
            "longitude": 127.00383,
        },
        "sources": [
            {
                "label": "담양군 버스정보시스템",
                "url": "http://bis.damyang.go.kr/busmap/lineSearch",
                "checkedDate": "2026-08-01",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "label": "한국대나무박물관(담양군)",
                "url": "https://www.damyang.go.kr/museum/index.damyang",
                "checkedDate": "2026-08-02",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
        ],
    },
    # ------------------------------------------------------------------
    # NJ_LOW_01
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "NJ_LOW_01",
        "title": "나주 읍성·곰탕 저환승 코스",
        "region": "나주",
        "courseType": "LOW_TRANSFER",
        "departurePoint": "USQUARE",
        "applicableDays": ["SATURDAY"],
        "timeType": "SIX_HOURS",
        "verificationStatus": "PARTIALLY_VERIFIED",
        "publishable": False,
        "exposureTier": "MANUAL_REVIEW",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-naju.svg",
        "tags": ["역사·문화", "음식·시장", "감성기록"],
        "preferences": ["HISTORY_CULTURE", "FOOD_MARKET", "MEMORY"],
        "totalMinutes": {"min": 279, "plan": 289, "max": 299},
        "walkingMinutes": {"min": 27, "plan": 35, "max": 39},
        "insideWalkingMinutes": 2,
        "transferCount": 0,
        "roundTripTransitMinutes": 84,
        "localTransitMinutes": 0,
        "stayMinutes": 140,
        "sheetFatigueLevel": "MEDIUM",
        "schedule": {
            "departureTime": "08:45",
            "plannedReturnTime": "13:49",
            "latestReturnTime": "14:34",
            "returnLegMinutes": {"min": 58, "plan": 59, "max": 62},
            "returnTransport": {
                "type": "SCHEDULED_SERVICE",
                "segmentId": "NJ_LOW_01-S2",
                "serviceDay": "SATURDAY",
                "plannedDeparture": "13:05",
                "plannedBoardingAfter": None,
                "alternativeDepartures": ["13:35", "13:50"],
                "departureWindow": None,
                "headwayMinutes": None,
                "ticketingModel": "ONSITE_TICKET",
                "stationArrivalBufferMinutes": 15,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "USER_VERIFIED_TIMETABLE+ONSITE_TICKET",
                "operatingModel": "계획 회차·현장예매형",
                "note": "나주 도착 직후 13:05 귀가표를 확보하고, 불가하면 대체 회차를 확인합니다.",
            },
            "bookingRequired": True,
            "bookingNote": "일반편은 현장예매만 가능 표시가 있어 나주 도착 직후 귀가표를 먼저 확보합니다.",
            "returnBufferMinutes": 15,
        },
        "recommendationReasons": [
            "나주터미널과 읍성권을 직행 시외버스와 도보로만 연결해 환승이 0회입니다.",
            "금성관·목사내아·곰탕거리가 도보 10분 권역 안에 모여 있습니다.",
            "계획 기준 13:49 유스퀘어 도착으로 6시간 안에 귀가가 끝납니다.",
        ],
        "description": "직행 시외버스로 나주읍성권에 들어가 금성관·목사내아·나주곰탕거리를 환승 없이 잇는 코스입니다.",
        "cautions": [
            "저피로가 아니라 저환승 코스입니다. 총 도보는 계획 35분입니다.",
            "귀가편 일반버스는 현장예매 조건이 있어 도착 직후 승차권을 확보해야 합니다.",
        ],
        "manualChecks": [
            "이용일 왕편 회차 재확인(09:05 일반 / 대체 09:30 우등·09:45 일반)",
            "나주 도착 직후 귀가표 확보",
            "출입구 기준 도보 3건",
        ],
        "itinerary": [
            {
                "id": "NJ_LOW_01-S1",
                "time": "08:45",
                "name": "유스퀘어 → 나주버스터미널",
                "type": "transport",
                "durationMinutes": 55,
                "note": "09:05 일반 직행 계획 회차(약 40분). 일반 4,300원·우등 6,800원.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "나주버스터미널", "latitude": 35.02058, "longitude": 126.71947},
            },
            {
                "id": "NJ_LOW_01-W1",
                "time": "09:45",
                "name": "나주버스터미널 → 금성관",
                "type": "walk",
                "durationMinutes": 10,
                "note": "나주읍성 진입. 로드뷰 확인 결과 계획값 유지.",
                "segmentType": "FIXED_PLAN",
                "verificationStatus": "VERIFIED_MAP",
            },
            {
                "id": "NJ-001",
                "time": "09:55",
                "name": "금성관",
                "type": "place",
                "durationMinutes": 40,
                "note": "나주목의 행정 중심이었던 객사. 행사·공사 통제 여부만 확인합니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "나주 금성관", "latitude": 35.02996, "longitude": 126.71603},
            },
            {
                "id": "NJ_LOW_01-W2",
                "time": "10:35",
                "name": "금성관 → 나주목사내아",
                "type": "walk",
                "durationMinutes": 3,
                "note": "읍성권 인접 구간.",
                "segmentType": "FIXED_PLAN",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "id": "NJ-002",
                "time": "10:38",
                "name": "나주목사내아(금학헌)",
                "type": "place",
                "durationMinutes": 40,
                "note": "조선시대 지방관의 생활 공간. 숙박·행사 운영 범위는 현장 안내를 따릅니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "나주목사내아", "latitude": 35.02963, "longitude": 126.71556},
            },
            {
                "id": "NJ_LOW_01-W3",
                "time": "11:18",
                "name": "나주목사내아 → 나주곰탕거리",
                "type": "walk",
                "durationMinutes": 7,
                "note": "선택한 식당 위치에 따라 변동됩니다.",
                "segmentType": "RANGE",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "id": "NJ_MEAL",
                "time": "11:25",
                "name": "나주곰탕거리",
                "type": "food",
                "durationMinutes": 60,
                "note": "하얀집·노안집·남평할매집·청산옥 중 영업·대기 상황이 좋은 곳을 선택합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "나주곰탕거리", "latitude": 35.02958, "longitude": 126.71683},
            },
            {
                "id": "NJ_LOW_01-W4",
                "time": "12:25",
                "name": "나주곰탕거리 → 나주버스터미널",
                "type": "walk",
                "durationMinutes": 15,
                "note": "선택 식당에 따라 약 10~20분. 계획값 15분.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "NJ_LOW_01-S2",
                "time": "13:05",
                "name": "나주버스터미널 → 유스퀘어",
                "type": "transport",
                "durationMinutes": 59,
                "note": "13:05 일반 직행(약 44분). 대체 13:35 우등·13:50 일반.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {
                    "name": "유스퀘어(광주종합버스터미널)",
                    "latitude": 35.16018,
                    "longitude": 126.87849,
                },
            },
        ],
        "localFood": [
            {
                "id": "NJ_MEAL_01",
                "name": "하얀집",
                "description": "08:00~20:00, 매주 수요일 휴무. 영업 중이며 대기 20분 이하이면 1순위로 선택합니다.",
                "tags": ["나주곰탕거리", "1순위"],
            },
            {
                "id": "NJ_MEAL_02",
                "name": "노안집",
                "description": "07:00~20:00, 매주 월요일 휴무. 1순위 휴무·혼잡 시 선택합니다.",
                "tags": ["나주곰탕거리", "2순위"],
            },
            {
                "id": "NJ_MEAL_03",
                "name": "남평할매집",
                "description": "08:00~20:00, 매주 화요일 휴무. 앞선 후보 이용이 어려울 때 선택합니다.",
                "tags": ["나주곰탕거리", "3순위"],
            },
            {
                "id": "NJ_MEAL_04",
                "name": "청산옥",
                "description": "11:30~20:00, 연중무휴. 11:30 이후 일정에서만 사용합니다.",
                "tags": ["나주곰탕거리", "일반식 대체"],
            },
        ],
        "localPoints": [
            {
                "id": "NJ-001",
                "title": "짧은 도보로 잇는 역사와 음식",
                "description": "금성관은 나주목의 행정 중심축이었고, 목사내아·곰탕거리와 가까워 별도 교통 없이 연결됩니다.",
                "tags": ["역사·문화"],
            },
            {
                "id": "NJ-002",
                "title": "행정 공간과 생활 공간의 대비",
                "description": "객사인 금성관과 지방관의 살림집인 목사내아를 나란히 비교해 볼 수 있습니다.",
                "tags": ["역사·문화", "감성기록"],
            },
        ],
        "scenePrompts": [
            "넓은 마당 너머로 정면이 보이는 금성관",
            "마당과 한옥 문틀이 겹쳐지는 장면",
            "곰탕 한 그릇과 오래된 가게 간판",
        ],
        "primaryDestination": {
            "name": "나주 금성관",
            "latitude": 35.02996,
            "longitude": 126.71603,
        },
        "sources": [
            {
                "label": "나주시 문화관광(읍성권)",
                "url": "https://www.naju.go.kr/tour/recommend/theme/eupseong",
                "checkedDate": "2026-08-01",
                "verificationStatus": "VERIFIED",
            },
            {
                "label": "유스퀘어 시외버스 예매",
                "url": "https://www.usquare.co.kr/kor/usquare/reservation.do",
                "checkedDate": "2026-08-01",
                "verificationStatus": "REFERENCE",
            },
        ],
    },
    # ------------------------------------------------------------------
    # NJ_NORMAL_01
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "NJ_NORMAL_01",
        "title": "나주 읍성·영산포 역사 코스",
        "region": "나주",
        "courseType": "NORMAL",
        "departurePoint": "USQUARE",
        "applicableDays": ["SATURDAY"],
        "timeType": "FULL_DAY",
        "verificationStatus": "PARTIALLY_VERIFIED",
        "publishable": False,
        "exposureTier": "DEMO_ONLY",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-naju.svg",
        "tags": ["역사·문화", "음식·시장", "감성기록"],
        "preferences": ["HISTORY_CULTURE", "FOOD_MARKET", "MEMORY"],
        "totalMinutes": {"min": 392, "plan": 422, "max": 452},
        "walkingMinutes": {"min": 24, "plan": 28, "max": 34},
        "insideWalkingMinutes": 4,
        "transferCount": 2,
        "roundTripTransitMinutes": 84,
        "localTransitMinutes": 50,
        "stayMinutes": 240,
        "sheetFatigueLevel": "HIGH",
        "schedule": {
            "departureTime": "07:40",
            "plannedReturnTime": "17:19",
            "latestReturnTime": "18:04",
            "returnLegMinutes": {"min": 49, "plan": 59, "max": 64},
            "returnTransport": {
                "type": "SCHEDULED_SERVICE",
                "segmentId": "NJ_NORMAL_01-S4",
                "serviceDay": "SATURDAY",
                "plannedDeparture": "16:35",
                "plannedBoardingAfter": None,
                "alternativeDepartures": ["17:20"],
                "departureWindow": None,
                "headwayMinutes": None,
                "ticketingModel": "ONSITE_TICKET",
                "stationArrivalBufferMinutes": 15,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "USER_VERIFIED_TIMETABLE+ONSITE_TICKET",
                "operatingModel": "계획 회차·현장예매형",
                "note": "16:35 회차를 우선 사용하고 17:20 회차를 대안으로 둡니다.",
            },
            "bookingRequired": True,
            "bookingNote": "16:35 또는 17:20 회차를 사용하며 현장예매 조건이 있어 도착 직후 귀가표를 확보합니다.",
            "returnBufferMinutes": 15,
        },
        "recommendationReasons": [
            "나주 160으로 읍성권과 영산포를 연결해 하루 동안 두 권역을 볼 수 있습니다.",
            "영산포 역사갤러리 12:00~13:00 폐관을 피해 식사 후 13시 이후 관람으로 배치했습니다.",
            "읍성권 식사를 먼저 끝내 현지버스 지연 시에도 일정이 무너지지 않습니다.",
        ],
        "description": "나주읍성권을 오전에 보고 나주 160으로 영산포로 이동해 근대 수운 도시의 흔적을 잇는 하루 코스입니다.",
        "cautions": [
            "환승 2회로 이동 부담이 큰 코스입니다.",
            "나주 160의 정류소 ID와 토요일 운행이 공식 확인되기 전까지 시연용으로만 사용합니다.",
        ],
        "manualChecks": [
            "나주 160 정류소 ID·토요일 운행",
            "영산포 역사갤러리 임시휴관(월요일 휴관, 12~13시 폐관)",
            "16:35 또는 17:20 귀가표 확보",
        ],
        "itinerary": [
            {
                "id": "NJ_NORMAL_01-S1",
                "time": "07:40",
                "name": "유스퀘어 → 나주버스터미널",
                "type": "transport",
                "durationMinutes": 54,
                "note": "07:55 일반 직행(44분). 대체 08:30 우등.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "나주버스터미널", "latitude": 35.02058, "longitude": 126.71947},
            },
            {
                "id": "NJ_NORMAL_01-W1",
                "time": "08:39",
                "name": "나주버스터미널 → 금성관·목사내아 권역",
                "type": "walk",
                "durationMinutes": 15,
                "note": "읍성 내부 이동 포함 추정값.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "NJ-001",
                "time": "08:54",
                "name": "금성관",
                "type": "place",
                "durationMinutes": 40,
                "note": "나주읍성권 중심 문화재.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "나주 금성관", "latitude": 35.02996, "longitude": 126.71603},
            },
            {
                "id": "NJ-002",
                "time": "09:34",
                "name": "나주목사내아(금학헌)",
                "type": "place",
                "durationMinutes": 40,
                "note": "금성관과 인접해 추가 교통이 필요 없습니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "나주목사내아", "latitude": 35.02963, "longitude": 126.71556},
            },
            {
                "id": "NJ_MEAL_SHARED",
                "time": "10:14",
                "name": "나주곰탕거리(읍성권 식사)",
                "type": "food",
                "durationMinutes": 60,
                "note": "영산포 이동 전 읍성권에서 식사를 끝내 현지버스 지연에 대비합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "나주곰탕거리", "latitude": 35.02958, "longitude": 126.71683},
            },
            {
                "id": "NJ_NORMAL_01-W2",
                "time": "11:14",
                "name": "나주곰탕거리 → 나주터미널 정류소",
                "type": "walk",
                "durationMinutes": 5,
                "note": "나주 160 승차 정류소로 이동.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "NJ_NORMAL_01-S2",
                "time": "11:19",
                "name": "나주터미널 인근 → 영산포",
                "type": "transport",
                "durationMinutes": 25,
                "note": "나주 160 (배차 15~20분). 정류소 ID·토요일 운행 공식 확인 필요.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "isTransfer": True,
            },
            {
                "id": "NJ_NORMAL_01-W3",
                "time": "11:44",
                "name": "영산포 정류소 → 홍어거리·역사갤러리",
                "type": "walk",
                "durationMinutes": 8,
                "note": "하차 정류소 확정 후 재계산 필요.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "NJ_HONGEO",
                "time": "11:52",
                "name": "영산포 홍어거리",
                "type": "place",
                "durationMinutes": 60,
                "note": "역사갤러리 점심 폐관 시간대(12:00~13:00)를 거리 관찰로 채웁니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "영산포 홍어거리", "latitude": 34.99920, "longitude": 126.71180},
            },
            {
                "id": "NJ-006",
                "time": "13:00",
                "name": "영산포 역사갤러리",
                "type": "place",
                "durationMinutes": 40,
                "note": "10:00~17:00, 12:00~13:00 폐관, 월요일 휴관, 무료. 문의 061-331-1755.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "영산포 역사갤러리", "latitude": 34.99930, "longitude": 126.71218},
            },
            {
                "id": "NJ_NORMAL_01-S3",
                "time": "14:40",
                "name": "영산포 → 나주버스터미널",
                "type": "transport",
                "durationMinutes": 25,
                "note": "나주 160 복귀. 16:35 귀가편 기준 여유를 확보합니다.",
                "segmentType": "HEADWAY",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "isTransfer": True,
            },
            {
                "id": "NJ_NORMAL_01-S4",
                "time": "16:35",
                "name": "나주버스터미널 → 유스퀘어",
                "type": "transport",
                "durationMinutes": 50,
                "note": "16:35 또는 17:20 회차. 현장예매형이므로 도착 직후 승차권 확보.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {
                    "name": "유스퀘어(광주종합버스터미널)",
                    "latitude": 35.16018,
                    "longitude": 126.87849,
                },
            },
        ],
        "localFood": [
            {
                "id": "NJ_MEAL_SHARED",
                "name": "나주곰탕거리 후보군(NJ_MEAL_01~04)",
                "description": "읍성권에서 식사를 끝내고 영산포는 간식·관찰 중심으로 운영합니다. 현지버스 지연 시 영산포 식사는 생략합니다.",
                "tags": ["나주곰탕거리", "공유 후보군"],
            },
        ],
        "localPoints": [
            {
                "id": "NJ-006",
                "title": "영산강 수운이 만든 근대 도시",
                "description": "영산강 수운과 근대 상업도시 영산포의 변화를 기록한 전시 공간으로, 홍어거리 식사와 연결됩니다.",
                "tags": ["역사·문화"],
            },
        ],
        "scenePrompts": [
            "옛 영산포 거리 사진과 현재 골목의 비교",
            "영산강과 근대 건물이 함께 보이는 장면",
            "기둥과 처마가 반복되는 금성관 측면 구도",
        ],
        "primaryDestination": {
            "name": "영산포 역사갤러리",
            "latitude": 34.99930,
            "longitude": 126.71218,
        },
        "sources": [
            {
                "label": "나주시 버스정보시스템",
                "url": "http://bis.naju.go.kr",
                "checkedDate": "2026-08-01",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "label": "나주시 문화관광(영산포 역사갤러리)",
                "url": "https://www.naju.go.kr/tour/sights/cultural_assets/heritage_material?mode=view&idx=300",
                "checkedDate": "2026-08-02",
                "verificationStatus": "VERIFIED",
            },
        ],
    },
    # ------------------------------------------------------------------
    # MP_LOW_01
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "MP_LOW_01",
        "title": "목포역 근대역사·노적봉 코스",
        "region": "목포",
        "courseType": "LOW_TRANSFER_WALKING",
        "departurePoint": "GWANGJU_SONGJEONG",
        "applicableDays": ["SATURDAY"],
        "timeType": "SIX_HOURS",
        "verificationStatus": "PARTIALLY_VERIFIED",
        "publishable": False,
        "exposureTier": "MANUAL_REVIEW",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-mokpo.svg",
        "tags": ["역사·문화", "자연·산책", "음식·시장"],
        "preferences": ["HISTORY_CULTURE", "NATURE_WALK", "FOOD_MARKET"],
        "totalMinutes": {"min": 318, "plan": 359, "max": 396},
        "walkingMinutes": {"min": 28, "plan": 39, "max": 46},
        "insideWalkingMinutes": 3,
        "transferCount": 0,
        "roundTripTransitMinutes": 140,
        "localTransitMinutes": 0,
        "stayMinutes": 180,
        "sheetFatigueLevel": "HIGH",
        "schedule": {
            "departureTime": "08:10",
            "plannedReturnTime": "14:09",
            "latestReturnTime": "15:20",
            "returnLegMinutes": {"min": 55, "plan": 70, "max": 85},
            "returnTransport": {
                "type": "RESERVATION_REQUIRED",
                "segmentId": "MP_LOW_01-S2",
                "serviceDay": "SATURDAY",
                "plannedDeparture": None,
                "plannedBoardingAfter": None,
                "alternativeDepartures": [],
                "departureWindow": {"start": "13:30", "end": "14:30"},
                "headwayMinutes": None,
                "ticketingModel": "ADVANCE_RESERVATION",
                "stationArrivalBufferMinutes": 35,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "OFFICIAL_BOOKING",
                "operatingModel": "이용일 왕복 선예매형",
                "note": "왕복 열차를 먼저 예매하고 귀가편 출발 30~40분 전 목포역에 복귀합니다.",
            },
            "bookingRequired": True,
            "bookingNote": "왕복 열차를 먼저 예매한 뒤 실제 편성에 맞춰 일정을 재계산합니다.",
            "returnBufferMinutes": 35,
        },
        "recommendationReasons": [
            "목포역 원도심을 환승 없이 걸어 연결하는 도보형 코스입니다.",
            "근대역사관 1관과 노적봉이 도보 8분 거리로 이어집니다.",
            "귀가 열차 30~40분 전 목포역 복귀 규칙을 일정에 반영했습니다.",
        ],
        "description": "광주송정에서 열차로 목포역에 도착해 근대역사관과 노적봉을 원도심 도보로 잇는 코스입니다.",
        "cautions": [
            "화면에 저피로로 표기하지 않습니다. 총 도보 39분·피로도 HIGH입니다.",
            "왕복 열차를 먼저 예매해야 실제 일정이 확정됩니다.",
        ],
        "manualChecks": [
            "왕복 열차 예매(KTX/SRT/ITX/무궁화 중 가능편)",
            "목포역 기준 도보 4건 실측",
            "식사 후보 영업·대기",
        ],
        "itinerary": [
            {
                "id": "MP_LOW_01-S1",
                "time": "08:10",
                "name": "광주송정역 → 목포역",
                "type": "transport",
                "durationMinutes": 70,
                "note": "열차별 소요시간 편차가 커 실제 예매편으로 일정을 재계산합니다.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "목포역", "latitude": 34.79131, "longitude": 126.38843},
            },
            {
                "id": "MP_LOW_01-W1",
                "time": "09:20",
                "name": "목포역 광장 출구 → 목포근대역사관 1관",
                "type": "walk",
                "durationMinutes": 13,
                "note": "약 750m. 기존 20분 과대값을 13분으로 수정했습니다.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP-001",
                "time": "09:33",
                "name": "목포근대역사관 1관",
                "type": "place",
                "durationMinutes": 70,
                "note": "09:00~18:00, 입장마감 17:00, 월요일 휴관.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "목포근대역사관 1관", "latitude": 34.78598, "longitude": 126.37990},
            },
            {
                "id": "MP_LOW_01-W2",
                "time": "10:43",
                "name": "근대역사관 1관 → 노적봉 입구",
                "type": "walk",
                "durationMinutes": 8,
                "note": "약 450m, 완만한 오르막 경사 보정 포함.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP-003",
                "time": "10:51",
                "name": "노적봉·유달산 입구",
                "type": "place",
                "durationMinutes": 50,
                "note": "정상 등산이 아니라 입구·노적봉 주변만 이용합니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "목포 노적봉", "latitude": 34.78802, "longitude": 126.37750},
            },
            {
                "id": "MP_LOW_01-W3",
                "time": "11:41",
                "name": "노적봉 → 원도심 식사 후보",
                "type": "walk",
                "durationMinutes": 8,
                "note": "선택한 식당에 따라 5~10분.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_MEAL",
                "time": "11:49",
                "name": "목포 원도심 식사",
                "type": "food",
                "durationMinutes": 60,
                "note": "성식당·장터식당·태동반점·유달콩물 등 후보 중 영업·대기 상황으로 선택합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "목포 원도심", "latitude": 34.78760, "longitude": 126.38200},
            },
            {
                "id": "MP_LOW_01-W4",
                "time": "12:49",
                "name": "식사 후보 → 목포역",
                "type": "walk",
                "durationMinutes": 10,
                "note": "귀가 열차 30~40분 전 역 도착 규칙을 적용합니다.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_LOW_01-S2",
                "time": "12:59",
                "name": "목포역 → 광주송정역",
                "type": "transport",
                "durationMinutes": 70,
                "note": "왕복 열차를 함께 예매한 뒤 실제 편성에 맞춰 재계산합니다.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "광주송정역", "latitude": 35.13600, "longitude": 126.79132},
            },
        ],
        "localFood": [
            {
                "id": "MP_MEAL_01",
                "name": "성식당",
                "description": "11:30~21:00, 매주 수요일 휴무, 브레이크 15:00~17:00. 대기 20분 이하일 때 1순위.",
                "tags": ["목포 원도심", "1순위"],
            },
            {
                "id": "MP_MEAL_04",
                "name": "유달콩물",
                "description": "08:00~17:30, 매주 화요일 휴무. 귀가 열차가 촉박할 때 적합한 가벼운 식사입니다.",
                "tags": ["목포 원도심", "빠른 식사"],
            },
            {
                "id": "MP_MEAL_07",
                "name": "해남해장국",
                "description": "07:00~19:00, 매주 화요일 휴무. 열차 시간이 촉박할 때 우선 검토합니다.",
                "tags": ["목포 원도심", "일반식"],
            },
        ],
        "localPoints": [
            {
                "id": "MP-001",
                "title": "옛 일본영사관 건물에서 보는 개항 도시",
                "description": "목포역·노적봉과 도보권이며 역사·감성기록 취향을 동시에 충족합니다.",
                "tags": ["역사·문화"],
            },
            {
                "id": "MP-003",
                "title": "원도심과 유달산이 만나는 지점",
                "description": "근대역사관과 가까워 짧은 산책으로 자연·역사 요소를 보완합니다.",
                "tags": ["자연·산책"],
            },
        ],
        "scenePrompts": [
            "붉은 벽돌 외관과 계단이 함께 보이는 정면",
            "노적봉 바위와 아래 원도심이 함께 보이는 장면",
            "유달산 입구에서 내려다본 항구 방향",
        ],
        "primaryDestination": {
            "name": "목포근대역사관 1관",
            "latitude": 34.78598,
            "longitude": 126.37990,
        },
        "sources": [
            {
                "label": "코레일 승차권 예매",
                "url": "https://korail.go.kr/ticket/main",
                "checkedDate": "2026-08-01",
                "verificationStatus": "REFERENCE",
            },
            {
                "label": "목포 관광지 관람안내",
                "url": "https://www.mokpo.go.kr/tour/tourguide/information/admission",
                "checkedDate": "2026-08-01",
                "verificationStatus": "VERIFIED",
            },
        ],
    },
    # ------------------------------------------------------------------
    # MP_NORMAL_02
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "MP_NORMAL_02",
        "title": "목포역 도보권 근대문화 확장 코스",
        "region": "목포",
        "courseType": "NORMAL_WALKING",
        "departurePoint": "GWANGJU_SONGJEONG",
        "applicableDays": ["SATURDAY"],
        "timeType": "FULL_DAY",
        "verificationStatus": "NEEDS_RECHECK",
        "publishable": False,
        "exposureTier": "DEMO_ONLY",
        "isPrimary": True,
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-mokpo.svg",
        "tags": ["역사·문화", "자연·산책", "음식·시장", "감성기록"],
        "preferences": ["HISTORY_CULTURE", "NATURE_WALK", "FOOD_MARKET", "MEMORY"],
        "totalMinutes": {"min": 383, "plan": 423, "max": 463},
        "walkingMinutes": {"min": 50, "plan": 60, "max": 70},
        "insideWalkingMinutes": 4,
        "transferCount": 0,
        "roundTripTransitMinutes": 140,
        "localTransitMinutes": 0,
        "stayMinutes": 223,
        "sheetFatigueLevel": "HIGH",
        "schedule": {
            "departureTime": "08:10",
            "plannedReturnTime": "15:13",
            "latestReturnTime": "17:40",
            "returnLegMinutes": {"min": 55, "plan": 70, "max": 85},
            "returnTransport": {
                "type": "RESERVATION_REQUIRED",
                "segmentId": "MP_NORMAL_02-S2",
                "serviceDay": "SATURDAY",
                "plannedDeparture": None,
                "plannedBoardingAfter": None,
                "alternativeDepartures": [],
                "departureWindow": None,
                "headwayMinutes": None,
                "ticketingModel": "ADVANCE_RESERVATION",
                "stationArrivalBufferMinutes": 40,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "DATE_DEPENDENT",
                "operatingModel": "이용일 왕복 선예매형",
                "note": "예매한 귀가 열차 출발 40분 전 목포역에 복귀합니다.",
            },
            "bookingRequired": True,
            "bookingNote": "왕복 열차 선예매 후 귀가 열차 40분 전 목포역 복귀.",
            "returnBufferMinutes": 40,
        },
        "recommendationReasons": [
            "현지버스를 쓰지 않고 목포역 도보권만으로 하루 일정을 완성합니다.",
            "노선 개편 영향이 없는 구간이라 교통 불확실성이 가장 낮습니다.",
            "근대역사관·근대역사문화공간·노적봉·시화골목을 하나의 도보 동선으로 잇습니다.",
        ],
        "description": "MP_NORMAL_01의 현지버스 불확실성을 제거하기 위해 채택한, 목포역 도보권 중심의 대체 주력 코스입니다.",
        "cautions": [
            "총 도보 60분으로 이동 부담이 매우 큽니다. 저피로로 표시하지 않습니다.",
            "원도심 도보 구간이 모두 추정값이며 지도 실측 대기 상태입니다.",
        ],
        "manualChecks": [
            "왕복 열차 예매",
            "목포 원도심 도보 구간 실측",
            "시화골목·목포진 역사공원 운영·기상 확인",
        ],
        "itinerary": [
            {
                "id": "MP_NORMAL_02-S1",
                "time": "08:10",
                "name": "광주송정역 → 목포역",
                "type": "transport",
                "durationMinutes": 70,
                "note": "왕복 열차 선예매.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "목포역", "latitude": 34.79131, "longitude": 126.38843},
            },
            {
                "id": "MP_NORMAL_02-W1",
                "time": "09:20",
                "name": "목포역 → 목포근대역사관 1관",
                "type": "walk",
                "durationMinutes": 13,
                "note": "약 810m, 13분 추정.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP-001",
                "time": "09:33",
                "name": "목포근대역사관 1관",
                "type": "place",
                "durationMinutes": 70,
                "note": "09:00~18:00, 입장마감 17:00, 월요일 휴관.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "목포근대역사관 1관", "latitude": 34.78598, "longitude": 126.37990},
            },
            {
                "id": "MP_NORMAL_02-W2",
                "time": "10:43",
                "name": "근대역사관 1관 → 목포근대역사문화공간",
                "type": "walk",
                "durationMinutes": 10,
                "note": "건물 외관 중심 자유 동선.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_CULTURE_ZONE",
                "time": "10:53",
                "name": "목포근대역사문화공간",
                "type": "place",
                "durationMinutes": 45,
                "note": "근대 건축물이 남은 거리 구역을 걸으며 관찰합니다.",
                "verificationStatus": "NEEDS_RECHECK",
                "place": {"name": "목포근대역사문화공간", "latitude": 34.78520, "longitude": 126.38060},
            },
            {
                "id": "MP_MEAL_NORMAL",
                "time": "11:38",
                "name": "목포 원도심 식사",
                "type": "food",
                "durationMinutes": 60,
                "note": "원도심 식사 후보군에서 브레이크타임 전에 이용합니다.",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "목포 원도심", "latitude": 34.78760, "longitude": 126.38200},
            },
            {
                "id": "MP_NORMAL_02-W3",
                "time": "12:38",
                "name": "원도심 식사 구역 → 노적봉·유달산 조각공원",
                "type": "walk",
                "durationMinutes": 18,
                "note": "경사 포함 추정값.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP-003",
                "time": "12:56",
                "name": "노적봉·유달산 조각공원",
                "type": "place",
                "durationMinutes": 30,
                "note": "입구 권역 위주로 이용합니다.",
                "verificationStatus": "VERIFIED",
                "place": {"name": "목포 노적봉", "latitude": 34.78802, "longitude": 126.37750},
            },
            {
                "id": "MP_NORMAL_02-W4",
                "time": "13:26",
                "name": "노적봉 → 시화골목 또는 목포진 역사공원",
                "type": "walk",
                "durationMinutes": 15,
                "note": "둘 중 운영·기상 조건이 좋은 곳을 선택합니다.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_SIHWA",
                "time": "13:41",
                "name": "시화골목 또는 목포진 역사공원",
                "type": "place",
                "durationMinutes": 18,
                "note": "기상·운영 상황에 따라 대체 가능한 선택 지점입니다.",
                "verificationStatus": "NEEDS_RECHECK",
                "place": {"name": "목포진 역사공원", "latitude": 34.78440, "longitude": 126.38150},
            },
            {
                "id": "MP_NORMAL_02-W5",
                "time": "13:59",
                "name": "마지막 장소 → 목포역",
                "type": "walk",
                "durationMinutes": 4,
                "note": "귀가 열차 40분 전 역 도착.",
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_NORMAL_02-S2",
                "time": "14:03",
                "name": "목포역 → 광주송정역",
                "type": "transport",
                "durationMinutes": 70,
                "note": "예매편 기준 소요시간으로 재계산합니다.",
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
                "place": {"name": "광주송정역", "latitude": 35.13600, "longitude": 126.79132},
            },
        ],
        "localFood": [
            {
                "id": "MP_MEAL_SHARED",
                "name": "목포 원도심 식사 후보군(MP_MEAL_01~08)",
                "description": "브레이크타임 전 점심 이용을 원칙으로 하며, 후보가 모두 혼잡하면 목포역 인근 백반·분식 구역으로 대체합니다.",
                "tags": ["목포 원도심", "공유 후보군"],
            },
        ],
        "localPoints": [
            {
                "id": "MP_CULTURE_ZONE",
                "title": "현지버스 없이 걷는 근대 도시",
                "description": "노선 개편 영향을 받지 않는 목포역 도보권만으로 근대문화·원도심·노적봉을 묶었습니다.",
                "tags": ["역사·문화"],
            },
        ],
        "scenePrompts": [
            "석조 외벽의 질감과 건물 모서리",
            "골목 담벼락의 시와 그림이 이어지는 장면",
            "창문 너머 원도심 풍경",
        ],
        "primaryDestination": {
            "name": "목포근대역사관 1관",
            "latitude": 34.78598,
            "longitude": 126.37990,
        },
        "sources": [
            {
                "label": "코레일 승차권 예매",
                "url": "https://korail.go.kr/ticket/main",
                "checkedDate": "2026-08-02",
                "verificationStatus": "REFERENCE",
            },
            {
                "label": "목포문화관광",
                "url": "https://www.mokpo.go.kr/tour",
                "checkedDate": "2026-08-01",
                "verificationStatus": "VERIFIED",
            },
        ],
    },
    # ------------------------------------------------------------------
    # MP_NORMAL_01 — 보류(HOLD) 코스. 추천 결과에 절대 노출되면 안 됩니다.
    # 코드가 노출 정책을 실제로 강제하는지 검증하기 위해 데이터로 남겨 둡니다.
    # ------------------------------------------------------------------
    {
        "schemaVersion": SCHEMA_VERSION,
        "id": "MP_NORMAL_01",
        "title": "목포 갓바위·자연사 문화 코스",
        "region": "목포",
        "courseType": "NORMAL",
        "departurePoint": "GWANGJU_SONGJEONG",
        "applicableDays": ["SATURDAY"],
        "timeType": "FULL_DAY",
        "verificationStatus": "NEEDS_RECHECK",
        "publishable": False,
        "exposureTier": "BLOCKED",
        "isPrimary": False,
        "holdReason": "낭만버스 22 노선 후보는 확인됐으나 토요일 공식 배차·운행횟수가 미확인입니다.",
        "replacedBy": "MP_NORMAL_02",
        "verifiedDate": "2026-08-02",
        "thumbnailUrl": "/images/course-mokpo.svg",
        "tags": ["역사·문화", "자연·산책"],
        "preferences": ["HISTORY_CULTURE", "NATURE_WALK", "MEMORY"],
        "totalMinutes": {"min": 380, "plan": 420, "max": 460},
        "walkingMinutes": {"min": 38, "plan": 41, "max": 50},
        "insideWalkingMinutes": 0,
        "transferCount": 2,
        "roundTripTransitMinutes": 108,
        "localTransitMinutes": 81,
        "stayMinutes": 190,
        "sheetFatigueLevel": "HIGH",
        "schedule": {
            "departureTime": "08:10",
            "plannedReturnTime": "15:10",
            "latestReturnTime": "17:30",
            "returnLegMinutes": {"min": 55, "plan": 70, "max": 85},
            "returnTransport": {
                "type": "RESERVATION_REQUIRED",
                "segmentId": "MP_NORMAL_01-S4",
                "serviceDay": "SATURDAY",
                "plannedDeparture": None,
                "plannedBoardingAfter": None,
                "alternativeDepartures": [],
                "departureWindow": None,
                "headwayMinutes": None,
                "ticketingModel": "ADVANCE_RESERVATION",
                "stationArrivalBufferMinutes": 40,
                "verificationStatus": "PARTIALLY_VERIFIED",
                "requiresDayOfCheck": True,
                "sourceValueType": "DATE_DEPENDENT",
                "operatingModel": "이용일 왕복 선예매형",
                "note": "보류 코스의 귀가 열차 구간이며 코스 노출 차단 상태와 별도로 관리합니다.",
            },
            "bookingRequired": True,
            "bookingNote": None,
            "returnBufferMinutes": 40,
        },
        "recommendationReasons": [
            "갓바위 문화권의 실내외 관광지를 한 번에 묶는 설계안입니다.",
        ],
        "description": "보류 코스입니다. 낭만버스 22의 토요일 공식 배차가 확인되기 전까지 사용자 추천에서 제외합니다.",
        "cautions": [
            "추천 결과·사용자 테스트 표본에서 완전히 제외되는 BLOCKED 코스입니다.",
        ],
        "manualChecks": [
            "낭만22 공식 토요일 배차·운행횟수",
            "목포시 정류소 ID",
        ],
        "itinerary": [
            {
                "id": "MP_NORMAL_01-S1",
                "time": "08:10",
                "name": "광주송정역 → 목포역",
                "type": "transport",
                "durationMinutes": 70,
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "id": "MP_NORMAL_01-S2",
                "time": "09:20",
                "name": "목포역권 → 목포자연사박물관",
                "type": "transport",
                "durationMinutes": 46,
                "note": "낭만버스 22(대체 22-1·22-2). 토요일 배차 미확인.",
                "segmentType": "HEADWAY",
                "verificationStatus": "NEEDS_RECHECK",
                "isTransfer": True,
            },
            {
                "id": "MP-005",
                "time": "10:06",
                "name": "목포자연사박물관",
                "type": "place",
                "durationMinutes": 90,
                "verificationStatus": "VERIFIED",
            },
            {
                "id": "MP_NORMAL_01-W1",
                "time": "11:36",
                "name": "자연사박물관 → 갓바위 해상보행교",
                "type": "walk",
                "durationMinutes": 10,
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP-004",
                "time": "11:46",
                "name": "갓바위 해상보행교",
                "type": "place",
                "durationMinutes": 40,
                "verificationStatus": "VERIFIED",
            },
            {
                "id": "MP_NORMAL_01-W2",
                "time": "12:26",
                "name": "갓바위 → 평화광장",
                "type": "walk",
                "durationMinutes": 20,
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MPN_MEAL",
                "time": "12:46",
                "name": "평화광장 식사",
                "type": "food",
                "durationMinutes": 60,
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
            {
                "id": "MP_NORMAL_01-S3",
                "time": "13:46",
                "name": "평화광장 → 목포역권",
                "type": "transport",
                "durationMinutes": 35,
                "note": "공식 토요일 배차 확인 전 사용 금지.",
                "segmentType": "HEADWAY",
                "verificationStatus": "NEEDS_RECHECK",
                "isTransfer": True,
            },
            {
                "id": "MP_NORMAL_01-W3",
                "time": "14:21",
                "name": "근대역사관 정류소 → 목포역",
                "type": "walk",
                "durationMinutes": 11,
                "segmentType": "RANGE",
                "verificationStatus": "NEEDS_RECHECK",
            },
            {
                "id": "MP_NORMAL_01-S4",
                "time": "14:32",
                "name": "목포역 → 광주송정역",
                "type": "transport",
                "durationMinutes": 38,
                "segmentType": "TIMETABLE",
                "verificationStatus": "PARTIALLY_VERIFIED",
            },
        ],
        "localFood": [],
        "localPoints": [],
        "scenePrompts": [],
        "primaryDestination": {
            "name": "목포자연사박물관",
            "latitude": 34.80740,
            "longitude": 126.37570,
        },
        "sources": [
            {
                "label": "목포시 노선DB(2026-07-23 공공데이터)",
                "url": "https://www.mokpo.go.kr/www/life_welfare/traffic/route_map",
                "checkedDate": "2026-08-02",
                "verificationStatus": "NEEDS_RECHECK",
            },
        ],
    },
]


COURSE_INDEX: dict[str, dict[str, Any]] = {
    course["id"]: course for course in COURSE_DETAILS
}
